blank_issues_enabled: false
contact_links:
  - name: ğŸ“„ erzwingungshaft - Documentation
    url: https://github.com/it-at-m/erzwingungshaft/issues/new/choose
    about: Open an issue in erzwingungshaft if the topic is related to the web documentation
  - name: ğŸ’¡ Discussions - Ideas
    url: https://github.com/it-at-m/erzwingungshaft-templates/discussions/categories/ideas
    about: Feel free to share ideas for the project that are to vague to create a dedicated issue beforehand
  - name: â‰ Discussions - Q&A
    url: https://github.com/it-at-m/erzwingungshaft-templates/discussions/categories/q-a
    about: Please ask questions here
  - name: ğŸ—¨ Discussions - General
    url: https://github.com/it-at-m/erzwingungshaft-templates/discussions/categories/general
    about: Discuss more general topics here
